export type Movie = {
  id: number;
  title: string;
  subtitle: string;
  year: number;
  rating: number;
  duration: string;
  genres: string[];
  description: string;
  poster: string;
  backdrop: string;
  badge: string;
  category: 'popular' | 'top-rated' | 'upcoming';
};

export const popularMovies: Movie[] = [
  {
    id: 1,
    title: 'Dune: Part Two',
    subtitle: 'The desert is not the only place where empires are made.',
    year: 2024,
    rating: 8.7,
    duration: '2h 46m',
    genres: ['Sci-Fi', 'Adventure'],
    description: 'Paul Atreides joins forces with Chani and the Fremen while facing the enemies who destroyed his family.',
    poster: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05J7P1s.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8b8R8l88Qje9dn9OE8PY05J7P1s.jpg',
    badge: 'Popular',
    category: 'popular',
  },
  {
    id: 2,
    title: 'Oppenheimer',
    subtitle: 'The cost of genius is measured in human lives.',
    year: 2023,
    rating: 8.6,
    duration: '3h 0m',
    genres: ['Drama', 'History'],
    description: 'A tense, powerful portrait of the scientist behind the atomic bomb and the era he helped define.',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    badge: 'Hot',
    category: 'popular',
  },
  {
    id: 3,
    title: 'Interstellar',
    subtitle: 'Mankind was born on Earth. It was never meant to die here.',
    year: 2014,
    rating: 8.7,
    duration: '2h 49m',
    genres: ['Sci-Fi', 'Drama'],
    description: 'A team of explorers travel through a wormhole in search of a new home for humanity amid an Earth crisis.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    badge: 'Classic',
    category: 'popular',
  },
  {
    id: 4,
    title: 'Spider-Man: Across the Spider-Verse',
    subtitle: 'The multiverse is bigger than you think.',
    year: 2023,
    rating: 8.4,
    duration: '2h 20m',
    genres: ['Animation', 'Action'],
    description: 'Miles Morales returns for a dramatic new adventure across a beautifully fractured multiverse.',
    poster: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    badge: 'Trending',
    category: 'popular',
  },
  {
    id: 5,
    title: 'The Batman',
    subtitle: 'Justice is a shadow that hunts the night.',
    year: 2022,
    rating: 8.3,
    duration: '2h 56m',
    genres: ['Action', 'Crime'],
    description: 'Batman uncovers corruption in Gotham while pursuing the Riddler and the city’s darkest secrets.',
    poster: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    badge: 'New',
    category: 'popular',
  },
  {
    id: 6,
    title: 'Avatar: The Way of Water',
    subtitle: 'The journey continues beneath the waves.',
    year: 2022,
    rating: 7.8,
    duration: '3h 12m',
    genres: ['Sci-Fi', 'Adventure'],
    description: 'Jake Sully and Neytiri face a new chapter of survival, family, and conflict among the Na’vi.',
    poster: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    badge: 'Epic',
    category: 'popular',
  },
  {
    id: 7,
    title: 'John Wick: Chapter 4',
    subtitle: 'No one leaves alive if the price is right.',
    year: 2023,
    rating: 8.1,
    duration: '2h 49m',
    genres: ['Action', 'Thriller'],
    description: 'John Wick continues his relentless pursuit of vengeance against the High Table.',
    poster: 'https://image.tmdb.org/t/p/w500/vZloFAK7NmLMwh2idXqfC4eD7G6.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/vZloFAK7NmLMwh2idXqfC4eD7G6.jpg',
    badge: 'Action',
    category: 'popular',
  },
  {
    id: 8,
    title: 'Barbie',
    subtitle: 'The world is just a little more colorful.',
    year: 2023,
    rating: 7.4,
    duration: '1h 54m',
    genres: ['Comedy', 'Fantasy'],
    description: 'Barbie and Ken navigate a reality shift that turns their perfect world upside down.',
    poster: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    badge: 'Fan Favorite',
    category: 'popular',
  },
];

export const topRatedMovies: Movie[] = [
  {
    id: 9,
    title: 'The Shawshank Redemption',
    subtitle: 'Hope can be found in a prison cell.',
    year: 1994,
    rating: 9.3,
    duration: '2h 22m',
    genres: ['Drama', 'Crime'],
    description: 'A banker who is sentenced to life in prison forms an unlikely friendship with a fellow inmate.',
    poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    badge: 'Top Rated',
    category: 'top-rated',
  },
  {
    id: 10,
    title: 'The Godfather',
    subtitle: 'A family. A legacy. A kingdom of power.',
    year: 1972,
    rating: 9.2,
    duration: '2h 55m',
    genres: ['Crime', 'Drama'],
    description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    badge: 'Classic',
    category: 'top-rated',
  },
  {
    id: 11,
    title: 'The Dark Knight',
    subtitle: 'The night is darkest before the dawn.',
    year: 2008,
    rating: 9.0,
    duration: '2h 32m',
    genres: ['Action', 'Crime'],
    description: 'Batman battles the Joker in a city torn apart by fear and chaos.',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    badge: 'Masterpiece',
    category: 'top-rated',
  },
  {
    id: 12,
    title: '12 Angry Men',
    subtitle: 'Justice starts with one decisive voice.',
    year: 1957,
    rating: 9.0,
    duration: '1h 36m',
    genres: ['Drama'],
    description: 'A jury is forced to revisit a murder case after one juror doubts the evidence.',
    poster: 'https://image.tmdb.org/t/p/w500/ow3wq4WQ2SE9vJQw2t9l3y8N7dH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/ow3wq4WQ2SE9vJQw2t9l3y8N7dH.jpg',
    badge: 'Legend',
    category: 'top-rated',
  },
  {
    id: 13,
    title: 'Parasite',
    subtitle: 'The poor can only climb so far before the wealthy notice.',
    year: 2019,
    rating: 8.5,
    duration: '2h 12m',
    genres: ['Thriller', 'Drama'],
    description: 'A poor family infiltrates the household of a wealthy couple and begins to unravel their carefully hidden lives.',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    badge: 'Award Winner',
    category: 'top-rated',
  },
  {
    id: 14,
    title: 'Spirited Away',
    subtitle: 'A world of magic awaits beyond the ordinary door.',
    year: 2001,
    rating: 8.5,
    duration: '2h 5m',
    genres: ['Animation', 'Fantasy'],
    description: 'A young girl becomes trapped in a magical bathhouse and must find a way home.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    badge: 'Animated',
    category: 'top-rated',
  },
  {
    id: 15,
    title: 'Whiplash',
    subtitle: 'Discipline is the price of greatness.',
    year: 2014,
    rating: 8.5,
    duration: '1h 47m',
    genres: ['Drama', 'Music'],
    description: 'A gifted drummer enters a prestigious conservatory where the path to greatness becomes brutal.',
    poster: 'https://image.tmdb.org/t/p/w500/8r18B0eJ1m3Jbg6pnaqgYH5AS1o.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8r18B0eJ1m3Jbg6pnaqgYH5AS1o.jpg',
    badge: 'Must Watch',
    category: 'top-rated',
  },
  {
    id: 16,
    title: 'The Green Mile',
    subtitle: 'Every soul leaves a trace.',
    year: 1999,
    rating: 8.5,
    duration: '3h 9m',
    genres: ['Crime', 'Drama'],
    description: 'A death-row prison guard becomes fascinated by a condemned inmate with mysterious powers.',
    poster: 'https://image.tmdb.org/t/p/w500/velWPhVMQeQK5JLQeRrD5wHNE5m.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/velWPhVMQeQK5JLQeRrD5wHNE5m.jpg',
    badge: 'Epic',
    category: 'top-rated',
  },
];

export const upcomingMovies: Movie[] = [
  {
    id: 17,
    title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    subtitle: 'The future of Panem begins here.',
    year: 2023,
    rating: 7.2,
    duration: '2h 37m',
    genres: ['Action', 'Adventure'],
    description: 'A young Coriolanus Snow becomes involved in the brutal games and the politics of a fractured nation.',
    poster: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    badge: 'Coming Soon',
    category: 'upcoming',
  },
  {
    id: 18,
    title: 'Mad Max: Fury Road',
    subtitle: 'The road is a weapon and survival is a myth.',
    year: 2015,
    rating: 8.1,
    duration: '2h 0m',
    genres: ['Action', 'Sci-Fi'],
    description: 'A survivor of the apocalypse battles a tyrant and rides across the wasteland to freedom.',
    poster: 'https://image.tmdb.org/t/p/w500/8tZY0s6ecTTj8RaoRwQr2a2nY4U.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8tZY0s6ecTTj8RaoRwQr2a2nY4U.jpg',
    badge: 'Anniversary',
    category: 'upcoming',
  },
  {
    id: 19,
    title: 'Mission: Impossible – Dead Reckoning',
    subtitle: 'The mission is no longer the only thing at stake.',
    year: 2023,
    rating: 7.8,
    duration: '2h 43m',
    genres: ['Action', 'Thriller'],
    description: 'Ethan Hunt races against time to stop a weaponized AI from destroying global order.',
    poster: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    badge: 'New',
    category: 'upcoming',
  },
  {
    id: 20,
    title: 'Kingdom of the Planet of the Apes',
    subtitle: 'The future belongs to those who rise.',
    year: 2024,
    rating: 7.6,
    duration: '2h 25m',
    genres: ['Action', 'Sci-Fi'],
    description: 'A new era of apes begins as the world rebuilds itself after the fall of human civilization.',
    poster: 'https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1fM2mk1LwJ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gKzYx79y0AQTL4UAk1fM2mk1LwJ.jpg',
    badge: 'Featured',
    category: 'upcoming',
  },
  {
    id: 21,
    title: 'Furiosa: A Mad Max Saga',
    subtitle: 'Every scar is a story worth surviving.',
    year: 2024,
    rating: 7.5,
    duration: '2h 28m',
    genres: ['Action', 'Adventure'],
    description: 'Furiosa’s origin story unfolds in a brutal desert empire ruled by a ruthless warlord.',
    poster: 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    badge: 'Epic',
    category: 'upcoming',
  },
  {
    id: 22,
    title: 'A Quiet Place: Day One',
    subtitle: 'Silence is survival.',
    year: 2024,
    rating: 7.3,
    duration: '1h 59m',
    genres: ['Horror', 'Thriller'],
    description: 'A new chapter in the survival saga begins in a world where silence is the only shield.',
    poster: 'https://image.tmdb.org/t/p/w500/8cXbitsS6dWQ5L2t7uH1xJ5g3dV.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8cXbitsS6dWQ5L2t7uH1xJ5g3dV.jpg',
    badge: 'Preview',
    category: 'upcoming',
  },
  {
    id: 23,
    title: 'Gladiator II',
    subtitle: 'Some legacies are forged in blood.',
    year: 2024,
    rating: 7.1,
    duration: '2h 28m',
    genres: ['Action', 'Drama'],
    description: 'A new generation enters the arena as power, revenge, and ambition collide in ancient Rome.',
    poster: 'https://image.tmdb.org/t/p/w500/2y5j95hKk6CMZ2kgW0dEwAy0F8D.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/2y5j95hKk6CMZ2kgW0dEwAy0F8D.jpg',
    badge: 'Soon',
    category: 'upcoming',
  },
  {
    id: 24,
    title: 'The Marvels',
    subtitle: 'The universe bends when the stars align.',
    year: 2023,
    rating: 6.9,
    duration: '1h 45m',
    genres: ['Action', 'Adventure'],
    description: 'Carol, Monica, and Kamala are thrown together when the powers of the cosmos collide.',
    poster: 'https://image.tmdb.org/t/p/w500/1H5qN0M7XfYdixIuA0Zq99C8jVh.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/1H5qN0M7XfYdixIuA0Zq99C8jVh.jpg',
    badge: 'Marvel',
    category: 'upcoming',
  },
];

export const allMovies = [...popularMovies, ...topRatedMovies, ...upcomingMovies];

export const featuredMovie = popularMovies[0];

export const movieSections = [
  { title: 'Popular', key: 'popular', movies: popularMovies },
  { title: 'Top Rated', key: 'top-rated', movies: topRatedMovies },
  { title: 'Upcoming', key: 'upcoming', movies: upcomingMovies },
];

export function getMovieById(id: number | string): Movie | undefined {
  return allMovies.find((movie) => String(movie.id) === String(id));
}
